name: prism-api
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.4.6
  - fastapi=0.63.0
  - flake8=3.9.0
  - h11=0.12.0
  - httptools=0.1.1
  - idna=2.10
  - importlib-metadata=3.7.3
  - iniconfig=1.1.1
  - libcxx=11.1.0
  - libffi=3.3
  - libuv=1.41.0
  - mccabe=0.6.1
  - more-itertools=8.7.0
  - ncurses=6.2
  - openssl=1.1.1j
  - packaging=20.9
  - pip=21.0.1
  - pluggy=0.13.1
  - py=1.10.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydantic=1.8.1
  - pyflakes=2.2.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.9.2
  - python-dotenv=0.15.0
  - python_abi=3.9
  - pyyaml=5.4.1
  - readline=8.0
  - requests=2.25.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - starlette-base=0.13.6
  - tk=8.6.10
  - toml=0.10.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.4
  - uvicorn=0.13.4
  - uvloop=0.15.2
  - watchgod=0.6
  - websockets=8.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
