name: prism-api
channels:
  - conda-forge
  - defaults
  - rexchange
dependencies:
  - fastapi
  - flake8
  - httpx=0.17.*
  - pip
  - pydantic=1.8.*
  - pytest
  - pytest-cov
  - python>=3.9
  - requests
  - rexredis
  - uvicorn
  - click
  - pip:
    - ariadne
    - gql[aiohttp]==3.0.0a5
