##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prism-api
---
apiVersion: v1
kind: Service
metadata:
  name: prism-api
  labels:
    app: prism-api
    service: prism-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: prism-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prism-api
      version: v1
  template:
    metadata:
      labels:
        app: prism-api
        version: v1
    spec:
      serviceAccountName: prism-api
      containers:
      - image: prism-api:latest
        imagePullPolicy: IfNotPresent
        name: prism-api
        ports:
        - containerPort: 8000
        env:
        - name: APP_DEBUG
          value: "TRUE"
        - name: APP_CORS_ORIGINS
          value: "http://localhost,http://localhost:8000,http://localhost:3000"
        - name: APP_CORS_ORIGIN_REGEX
          value: "https?://.*\\.rex\\.sh"
        - name: REX_DS_REDIS_HOST
          value: redis
        - name: REX_DS_REDIS_PORT
          value: "6379"
        - name: REX_REXFLOW_HOST
          value: "http://ui-bridge.{deployment_id}:5051/graphql"
        - name: REX_REXFLOW_FLOWD_HOST
          value: "http://flowd.rexflow:9002"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: default
  name: prism-api
spec:
  gateways:
  - rexflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /prism-api/
    rewrite:
      uri: /
    route:
    - destination:
        host: prism-api.default.svc.cluster.local
        port:
          number: 80
