services:
 - name: prism-api
   externalPort: '80'
   internalPort: '8000'

ingress:
  enabled: true
  internet_facing: true
  authentication:
    employee: true

replicaCount: 3

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 0
  periodSecods: 5
  timeoutSeconds: 5
