nameOverride: prism-api
image:
  repository: rex/prism-api

services:
- name: prism-api
  externalPort: '80'
  internalPort: '8000'

ingress:
  enabled: true
  internet_facing: true
  authentication:
    employee: true

priorityClassName: shared-critical

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /health/status
    port: 8000
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5

resources:
  limits:
    memory: 256Mi
    cpu: 200m

env:
  LOG_LEVEL: INFO
  REX_REXFLOW_FLOWD_HOST: http://flowd.rexflow:9002
  OKTA_BASE_URI: https://dev-882393.okta.com/oauth2/default
  OKTA_CLIENT_ID: 0oa3l15id2wXRWdcQ4x7
  OKTA_ISSUER_URL: https://dev-882393.okta.com/oauth2/default
  OKTA_AUDIENCE: api://default
