import os


LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

REXUI_CALLBACK_HOST = os.getenv('REX_REXUI_SERVER_CALLBACK_HOST')
REXFLOW_FLOWD_HOST = os.getenv('REX_REXFLOW_FLOWD_HOST')
REXFLOW_EXECUTION_TIMEOUT = int(os.getenv('REX_REXFLOW_EXECUTION_TIMEOUT', 30))
